name: Make docs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python environment
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        pip3 install -r requirements-docs.txt
        pip3 install .

    - name: Build and deploy docs
      run: |
        . .venv/bin/activate
        mkdocs gh-deploy -s --force

