name: Test

on: 
  push:
    branches: 
      - '*'
      - '*/**'
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'LICENSE.txt'
      - 'CHANGELOG.md'
      - '.github/workflows/release.yml'
      - '.github/workflows/docs.yml'

jobs:
  matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy-3.8", "pypy-3.9"]
        exclude:
          - os: windows-latest
            python-version: "pypy-3.8" #no cryptography available there

    env:
      PGP_KEY_NAME: ${{ secrets.PGP_KEY_NAME }}
      PGP_KEY_PASSWD: ${{ secrets.PGP_KEY_PASSWD }}
      BSD_KEY: ${{ github.workspace }}/bsd-key
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preprare Keys
        shell: bash
        run: |
          export GNUPGHOME=$GITHUB_WORKSPACE/.gpg
          mkdir -p $GNUPGHOME
          echo -n "${{ secrets.PGP_KEY }}" | base64 --decode | gpg --import --batch --pinentry-mode=loopback
          echo -n "${{ secrets.BSD_KEY }}" > $GITHUB_WORKSPACE/bsd-key

      - name: Set up Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{matrix.python-version}}

      - name: Install Nox
        run: pip install Nox

      - name: Test
        shell: bash
        run: |
          export GNUPGHOME=$GITHUB_WORKSPACE/.gpg
          nox --sessions test --force-python ${{ steps.setup-python.outputs.python-path }}

